name: "Template-KeyVault-GetSecrets"

on:
  workflow_call:
    inputs:
      secrets:
        type: string
        required: true
      keyvault:
        type: string
        required: true
    secrets:
      azureEnviromentCredentials:
        required: true

jobs:
  LoadSecrets:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1
        name: Run Azure Login
        with:
          creds: ${{ secrets.azureEnviromentCredentials }}

      - name: Load KeyVault Secret(s)
        run: |
          OIFS=$IFS
          IFS=', '

          for secretname in ${{ inputs.secrets }}
          do
            # Do stuff with each word
            echo "----------------------- Loading secrets -----------------------------------------------------"
            echo $secretname
            secret=$(az keyvault secret show --name $secretname --vault-name ${{inputs.keyvault}})
            echo "::add-mask::$secret"
            
            echo "$secretname=$secret" >> GITHUB_OUTPUT
          done
          IFS=$OIFS