name: "Template-TF-Validate"
on:
  workflow_call:
    inputs:
      environmentName:
        type: string
        required: true
      goVersion:
        type: string
        required: true
      terraformVersion:
        type: string
        required: true
      runLayerTest:
        type: boolean
        required: true
        default: true
      keyVaultName:
        type: string
        required: true
      branchName:
        type: string
        required: true
    secrets:
      azureEnviromentCredentials:
        required: true

jobs:
  Validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          ref: ${{ inputs.branchName }}

      - name: Setup Toolset
        run: |
          ./setup-azcli.sh
          ./setup-gitleaks.sh
          ./setup-terraform.sh ${{ inputs.terraformVersion }}        
          ./setup-tflint.sh
          source ~/.bashrc
        working-directory: scripts/orchestrators

      - name: Run Gitleaks
        run: |
          source ./scanners.sh
          run_gitleaks './../../IAC/Terraform' 'sarif' 'info' 'true'
        working-directory: scripts/orchestrators

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: gitleaks-report
          path: scripts/orchestrators/gitleaks-report.*

      - name: Upload Gitleaks SARIF report to code scanning service
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: scripts/orchestrators/gitleaks-report.sarif

      - name: Run TF Lint
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
        run: |
          ./iac.tf.lint.sh
        working-directory: scripts/orchestrators
        shell: bash

      - uses: Azure/login@v1
        name: Run Azure Login
        with:
          creds: ${{ secrets.azureEnviromentCredentials }}

      # - uses: Azure/get-keyvault-secrets@v1
      #   name: Get KeyVault Secrets
      #   with:
      #     keyvault: ${{ github.event.inputs.keyVaultName }}
      #     secrets: "clientId, clientSecret, subscriptionId, tenantId, stateRg, stateContainer, stateStorageAccount"
      #   id: kvSecrets

      - name: Load KeyVault Secret(s)
        id: LoadSecrets
        env:
          KEYVAULT_NAME: ${{ inputs.keyVaultName }}
          SECRETS: "clientId, clientSecret, subscriptionId, tenantId, stateRg, stateContainer, stateStorageAccount"
        run: |
          OIFS=$IFS
          IFS=', '
          for secretname in $SECRETS
          do
           
            secret=$(az keyvault secret show --name $secretname --vault-name $KEYVAULT_NAME --query "value")
            if [[ $secretname == "tenantId" ]]; then
              echo "---tenantID value"
              echo $secret
            fi
            echo "::add-mask::$secret"           
            echo "$secretname=$secret" >> $GITHUB_OUTPUT
          done
          IFS=$OIFS

      - name: Run TF Validate
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
          ARM_SUBSCRIPTION_ID: ${{ steps.LoadSecrets.outputs.subscriptionId }}
          ARM_TENANT_ID: ${{ steps.LoadSecrets.outputs.tenantId }}
          ARM_CLIENT_ID: ${{ steps.LoadSecrets.outputs.clientId }}
          ARM_CLIENT_SECRET: ${{ steps.LoadSecrets.outputs.clientSecret }}
          STATE_RG: ${{ steps.LoadSecrets.outputs.stateRg }}
          STATE_STORAGE_ACCOUNT: ${{ steps.LoadSecrets.outputs.stateStorageAccount }}
          STATE_CONTAINER: ${{ steps.LoadSecrets.outputs.stateContainer }}
          ENVIRONMENT_NAME: ${{ inputs.environmentName }}
        run: |

          ./iac.tf.validate.sh
        working-directory: scripts/orchestrators
        shell: bash

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Run Layer Tests
        if: ${{ inputs.runLayerTest }}
        env:
          WORKSPACE_PATH: ${{ github.workspace }}
          ARM_SUBSCRIPTION_ID: ${{ steps.kvSecrets.outputs.subscriptionId }}
          ARM_TENANT_ID: ${{ steps.kvSecrets.outputs.tenantId }}
          ARM_CLIENT_ID: ${{ steps.kvSecrets.outputs.clientId }}
          ARM_CLIENT_SECRET: ${{ steps.kvSecrets.outputs.clientSecret }}
          STATE_RG: ${{ steps.kvSecrets.outputs.stateRg }}
          STATE_STORAGE_ACCOUNT: ${{ steps.kvSecrets.outputs.stateStorageAccount }}
          STATE_CONTAINER: ${{ steps.kvSecrets.outputs.stateContainer }}
          ENVIRONMENT_NAME: ${{ inputs.environmentName }}
          TEST_TAG: module_tests
        run: |
          ./iac.tf.test.sh

        working-directory: scripts/orchestrators
        shell: bash

      - uses: actions/upload-artifact@v3
        if: (success() || failure()) && ${{ inputs.runLayerTest }}
        with:
          name: Modules test results
          path: ./IAC/Terraform/test/terraform/*.xml

      - name: Publish Module Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ inputs.runLayerTest }}
        with:
          files: "./IAC/Terraform/test/terraform/*.xml"
          check_name: "Modules tests Results"
